# Generated by Django 5.1.1 on 2024-09-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shopentry_delete_moodentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopentry',
            name='locaiton',
            field=models.CharField(max_length=255),
        ),
    ]
