# Generated by Django 5.1.1 on 2024-09-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_shopentry_locaiton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopentry',
            old_name='locaiton',
            new_name='location',
        ),
    ]
