# Generated by Django 5.1.1 on 2024-09-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_locaiton_shopentry_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopentry',
            old_name='description',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='shopentry',
            name='price',
        ),
    ]
